// Keys retain upstream spelling. Labels translate historical polities and cultures, not only modern countries.
window.ATLAS_LABELS_ZH = {
  "?":"名称不详", "Abbasid Caliphate":"阿拔斯哈里发国", "Abdelouadides":"扎扬王朝",
  "Achaemenid Empire":"阿契美尼德帝国", "Aghlabid Emirate":"阿格拉布埃米尔国",
  "Akatziri":"阿卡齐里人", "Alamans":"阿勒曼尼人", "Alans":"阿兰人",
  "Almohad Caliphate":"穆瓦希德哈里发国", "Almoravid dynasty":"穆拉比特王朝",
  "Angevin Empire":"安茹帝国", "Arabian pastoral nomads":"阿拉伯游牧社群", "Arabs":"阿拉伯人",
  "Aragón":"阿拉贡", "Arameans":"阿拉米人", "Armenia":"亚美尼亚", "Armorica":"阿摩里卡",
  "Asturias":"阿斯图里亚斯", "Aures":"奥雷斯", "Avars":"阿瓦尔人", "Barghawata":"巴尔加瓦塔",
  "Basques":"巴斯克人", "Bedouins":"贝都因人", "Bell-shaped burials culture":"钟形墓葬文化",
  "Berber Tribes":"柏柏尔部落", "Berbers":"柏柏尔人", "Beylik of Aydin":"艾登贝伊国",
  "Bithynia":"比提尼亚", "Blue Horde":"蓝帐汗国", "Boihaenum":"波伊海姆", "Boii":"波伊人",
  "Bosnia":"波斯尼亚", "Bosporan Kingdom":"博斯普鲁斯王国", "Bosporian Kingdom":"博斯普鲁斯王国",
  "Britany":"布列塔尼", "Broërec":"布罗埃雷克", "Bulgar Khanate":"保加尔汗国", "Bulgars":"保加尔人",
  "Burgandy":"勃艮第", "Burgundians":"勃艮第人", "Buwayhid Emirates":"布韦希埃米尔诸国",
  "Byzantine Empire":"拜占庭帝国", "Caliphate of Córdoba":"科尔多瓦哈里发国",
  "Cappadocia":"卡帕多基亚", "Carolingian Empire":"加洛林帝国", "Carthage":"迦太基",
  "Carthaginian Empire":"迦太基势力", "Castile":"卡斯蒂利亚", "Castilla":"卡斯蒂利亚",
  "Caucasian Alans":"高加索阿兰人", "Celtiberians":"凯尔特伊比利亚人", "Celts":"凯尔特人",
  "Chelmia":"胡姆公国", "Chernoles culture":"切尔诺莱斯文化", "Cimerians":"辛梅里安人",
  "Comté de Toulouse":"图卢兹伯国", "Corsica":"科西嘉", "Crete":"克里特", "Croatia":"克罗地亚",
  "Croatian kingdom":"克罗地亚王国", "Cuman Khanates":"库曼汗国", "Cuman-Kipchak confederation":"库曼钦察联盟",
  "Cyprus":"塞浦路斯", "Czechs":"捷克人", "Dacia":"达契亚", "Dacians":"达契亚人",
  "Danube Bulgars":"多瑙河保加尔人", "Dardania":"达尔达尼亚", "Duchy of Benevento":"贝内文托公国",
  "Duchy of Swabia":"施瓦本公国", "East Francia":"东法兰克王国", "Eastern Roman Empire":"东罗马帝国",
  "Egypt":"埃及", "Emirate of Córdoba":"科尔多瓦埃米尔国", "Emirate of Sicily":"西西里埃米尔国",
  "Empire of Alexander":"亚历山大帝国", "England":"英格兰", "English territory":"英格兰领地",
  "Etrurians":"伊特鲁里亚人", "Fatimid Caliphate":"法蒂玛哈里发国", "France":"法国",
  "Frankish Kingdom":"法兰克王国", "Franks":"法兰克人", "Goths":"哥特人", "Granada":"格拉纳达",
  "Great Moravia":"大摩拉维亚", "Greek city-states":"希腊城邦", "Greek colonies":"希腊殖民地",
  "Hafsid Caliphate":"哈夫斯王朝", "Hallstatt culture":"哈尔施塔特文化", "Hittites":"赫梯人",
  "Holy Roman Empire":"神圣罗马帝国", "Hungary":"匈牙利", "Hunnic Empire":"匈人帝国",
  "Ibadites":"伊巴德派", "Idrisid Caliphate":"伊德里斯王朝", "Ilkhanate":"伊儿汗国",
  "Illyrians":"伊利里亚人", "Judea":"犹太地区", "Khanate of the Golden Horde":"金帐汗国",
  "Khazars":"可萨人", "Kievan Rus":"基辅罗斯", "Kyivan Rus":"基辅罗斯",
  "Kingdom of Antigonus":"安提柯王国", "Kingdom of David and Solomon":"大卫与所罗门王国",
  "Kingdom of France":"法兰西王国", "Kingdom of Gala":"加拉王国", "Kingdom of Georgia":"格鲁吉亚王国",
  "Kingdom of Hungary":"匈牙利王国", "Kingdom of Kassander":"卡山德王国",
  "Kingdom of Lysimachus":"利西马科斯王国", "Kingdom of Syphax":"西法克斯王国",
  "La Tène culture":"拉泰讷文化", "León":"莱昂", "Lombard duchies":"伦巴第诸公国",
  "Lombard principalities":"伦巴第诸侯国", "Macedon and Hellenic League":"马其顿与希腊联盟",
  "Magyars":"马扎尔人", "Mamluke Sultanate":"马穆鲁克苏丹国", "Mauretania":"毛里塔尼亚王国",
  "Mauri":"毛里人", "Merinides":"马林王朝", "Moldova":"摩尔达维亚", "Mongol Empire":"蒙古帝国",
  "Moravians":"摩拉维亚人", "Morocco":"摩洛哥", "Nabatean Kingdom":"纳巴泰王国",
  "Navarre":"纳瓦拉", "Neustria":"纽斯特里亚", "Numidia":"努米底亚", "Odrysian Kingdom":"奥德里西亚王国",
  "Ostrogoths":"东哥特人", "Ottoman Empire":"奥斯曼帝国", "Papal States":"教皇国",
  "Parthian Empire":"帕提亚帝国", "Pechenegs":"佩切涅格人", "Pergamon":"帕加马",
  "Persi":"波斯人", "Persia":"波斯", "Peshemegs":"佩舍梅格人（原数据称谓）",
  "Phrygians":"弗里吉亚人", "Poland":"波兰", "Poland-Lithuania":"波兰立陶宛",
  "Polyanians":"波利安人", "Portugal":"葡萄牙", "Principality of Galicia-Volhynia":"加利西亚沃里尼亚公国",
  "Principality of Kyiv":"基辅公国", "Principality of Wallachia":"瓦拉几亚公国",
  "Proto-Scythian culture":"原始斯基泰文化", "Proto-Slavs":"原始斯拉夫人",
  "Ptolemaic Kingdom":"托勒密王国", "Raška":"拉什卡", "Roman Empire":"罗马帝国",
  "Roman Republic":"罗马共和国", "Rome":"罗马", "Rome (Constantinus)":"罗马（君士坦丁）",
  "Rome (Diocletianus)":"罗马（戴克里先）", "Rome (Galerius)":"罗马（伽列里乌斯）",
  "Rome (Maximian)":"罗马（马克西米安）", "Ryazan":"梁赞", "Sabines":"萨宾人", "Sabini":"萨宾人",
  "Sabirs":"萨比尔人", "Saharan Nomadic Tribes":"撒哈拉游牧部落", "Saharan pastoral nomads":"撒哈拉游牧社群",
  "Samnites":"萨姆尼特人", "Sardinia":"撒丁岛", "Sarmates":"萨尔马提亚人",
  "Sasanian Empire":"萨珊帝国", "Scythians":"斯基泰人", "Seleucid Kingdom":"塞琉古王国",
  "Seljuk Caliphate":"塞尔柱统治区", "Seljuk Empire":"塞尔柱帝国", "Serbia":"塞尔维亚",
  "Sicily":"西西里", "Skirii":"斯基里人", "Slavic tribes":"斯拉夫部落",
  "Slavonic tribes":"斯拉夫部落", "Slavs":"斯拉夫人", "Suebi":"苏维汇人", "Thrace":"色雷斯",
  "Timurid Empire":"帖木儿帝国", "Touareg":"图阿雷格人", "Trebizond":"特拉比松",
  "Tuareg Nomadic Tribes":"图阿雷格游牧部落", "Tuaregs":"图阿雷格人",
  "Turingians":"图林根人", "Umayyad Caliphate":"倭马亚哈里发国", "Urartu":"乌拉尔图",
  "Urnfield cultures":"瓮棺文化", "Vandals":"汪达尔人", "Vasconia":"瓦斯科尼亚",
  "Venice":"威尼斯", "Visigothic Kingdom":"西哥特王国", "Visigoths":"西哥特人",
  "Warsenis":"瓦尔塞尼斯", "West Francia":"西法兰克王国", "Western Roman Empire":"西罗马帝国",
  "minor states":"小型政权", "state societies and Aramaean kingdoms":"地方国家与阿拉米诸王国"
};
